In [146]:
#In python we have only list, we do not have numpy arrays. numpy arrays we create using nnumpy fun
# from nnnumpy module...basically these are used for sciencetifc computinnng
# Scientific computinng means it is just collection of toools, techniques to solve problems in science and engg
#it contains n dimensional array
#numpy is official multidimensional container data
#nnumpy is very fast thann list

import numpy as np

In [6]:
lst1 = [1,2,3,4]

In [7]:
type(lst1)

list

In [8]:
a=np.array(lst1)

In [9]:
type(a)

numpy.ndarray

In [10]:
a

array([1, 2, 3, 4])

In [11]:
a.ndim

1

heterogenous or not
indexing
slicig
functions of numpy

In [12]:
#numpy arrays are heterogenous
list1 = [10,20,"Sachin",True]


In [13]:
type(list1)

list

In [14]:
list1

[10, 20, 'Sachin', True]

In [15]:
a = np.array(list1)

In [17]:
a

array(['10', '20', 'Sachin', 'True'], dtype='<U21')

In [16]:
type(a)
#therefore numpys are heterogenous (else it would through error)

numpy.ndarray

In [18]:
#indexing
a[2]

'Sachin'

In [19]:
a[1]

'20'

In [20]:
#slicing
a[:]  #selecting all the possible elements

array(['10', '20', 'Sachin', 'True'], dtype='<U21')

In [21]:
a[:3] # all elements from starting before 3rd index ie till 2nd index

array(['10', '20', 'Sachin'], dtype='<U21')

In [22]:
a[1:3]

array(['20', 'Sachin'], dtype='<U21')

In [23]:
#functions
#lets first understand 2d array and then will move to functions

list1 = [[1,2,3],[4,5,6],[6,7,8],[8,9,10]]

In [24]:
list1

[[1, 2, 3], [4, 5, 6], [6, 7, 8], [8, 9, 10]]

In [25]:
a = np.array(list1)

In [26]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [28]:
#dimension
a.ndim

2

In [30]:
#shape
a.shape

(4, 3)

In [31]:
#indexing for 2d array
a[0]

array([1, 2, 3])

In [32]:
a[1:3]

array([[4, 5, 6],
       [6, 7, 8]])

In [35]:
#Syntax
#a[rows, cols]

In [37]:
#---v1---
a[0:4, 1:2] #As we need all 4 rows, and 1st col
#It is column matrix 
#same we can write like below also

array([[2],
       [5],
       [7],
       [9]])

In [38]:
#----v2----
a[:,1]
#This is row matrix

array([2, 5, 7, 9])

In [39]:
#----v3----
a[:,1:2]

array([[2],
       [5],
       [7],
       [9]])

In [40]:
#to drag 5678
a[1:3,1:]

array([[5, 6],
       [7, 8]])

In [42]:
#to grab only 5
a[1:2,1:2]

array([[5]])

In [45]:
a[1,1]

5

In [46]:
#Lets check numpy arrays are mutable are not
a[1,1] = 100

In [47]:
a

array([[  1,   2,   3],
       [  4, 100,   6],
       [  6,   7,   8],
       [  8,   9,  10]])

In [48]:
#it is understood numpy arrays are mutable

In [49]:
#broadcasting in numpy arrays
a[1:]= 99

In [50]:
a

array([[ 1,  2,  3],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [51]:
#Converts all the rows starting from 1 into 99

In [52]:
a=np.arange(10)

In [53]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a=np.arange(10,2)

In [56]:
a
#it will not display anything as rhs nnumber must be big

array([], dtype=int64)

In [57]:
a=np.arange(10,40)

In [58]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [59]:
#stepsize in arange
a=np.arange(10,40,2)

In [60]:
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [61]:
a=np.arange(10,40,5)

In [62]:
a

array([10, 15, 20, 25, 30, 35])

In [63]:
#zeros function
a = np.zeros(3)
a

array([0., 0., 0.])

In [64]:
#It is giving 1d array of 3 zeros


In [67]:
a = np.zeros((3,2))
a
#It gives 3 row 3 col all zeros


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [69]:
#ones
a=np.ones((2,3))
a
#It give 2 row 3 col all 1's

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
#eye
a=np.eye(4)

In [74]:
a
#all diagonal it will put 1's

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [75]:
#linspace
a=np.linspace(10) #error as linspace should have 2 arguments

TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

In [76]:
a=np.linspace(10,20)

In [78]:
a
#it will return the evenly spaced numbers in a specified interval

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [79]:
a=np.linspace(10,20,5) #total 5 elements 

In [80]:
a

array([10. , 12.5, 15. , 17.5, 20. ])

In [81]:
a=np.linspace(10,20,10) #total 10 elements 

In [82]:
a

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [84]:
#min()
a.min()

10.0

In [86]:
#max()
a.max()

20.0

In [87]:
#argmin()
a.argmin()

0

In [88]:
#argmax()
a.argmax()

9

In [89]:
#rand()
b=np.random.rand(2)
b
#2 random numbers gets created

array([0.82206325, 0.26490078])

In [90]:
b=np.random.rand(3,3)
b

array([[0.82764679, 0.61580542, 0.77414408],
       [0.27484857, 0.02357297, 0.02958219],
       [0.08817846, 0.94547719, 0.06915409]])

In [91]:
#randint
c = np.random.randint(100)
c
#it will generate a random integer from 0 to 100

40

In [93]:
d = np.random.randint(1,100,10)
d
#it will generate 10 random integers from 0 to 100

array([59, 89, 51, 97, 91, 44, 11, 95, 76, 69])

In [107]:
#flatten - converts multi dimensional array into 1d array
f = np.arange(16)

In [108]:
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [109]:
g = f.reshape(4,4)

In [110]:
g
#become 4x4 matrix
#remember reshape will not happen for 3x4 etc

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
#ravel()
h = g.ravel()
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [112]:
h[6]=99

In [113]:
#effected in h
h

array([ 0,  1,  2,  3,  4,  5, 99,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [115]:
#effected in g
g

array([[ 0,  1,  2,  3],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
#flatten()
i=g.flatten()
i

array([ 0,  1,  2,  3,  4,  5, 99,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [117]:
i[3]=88


In [118]:
#effected in i
i

array([ 0,  1,  2, 88,  4,  5, 99,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [119]:
#not effected in g - This is what the difference between ravel and flatten
g

array([[ 0,  1,  2,  3],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [120]:
#transpose
j = np.transpose(g)
j
#rows becomes columns and vv

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2, 99, 10, 14],
       [ 3,  7, 11, 15]])

In [122]:
#new way of Transponse in python
k=j.T
k

array([[ 0,  1,  2,  3],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [123]:
#concatenate
l = np.concatenate((k,j))
l

array([[ 0,  1,  2,  3],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2, 99, 10, 14],
       [ 3,  7, 11, 15]])

In [124]:
#concatenate using column wise
l = np.concatenate((k,j),axis=1)
l

array([[ 0,  1,  2,  3,  0,  4,  8, 12],
       [ 4,  5, 99,  7,  1,  5,  9, 13],
       [ 8,  9, 10, 11,  2, 99, 10, 14],
       [12, 13, 14, 15,  3,  7, 11, 15]])

In [125]:
#split()
p = np.split(l,2)
p

[array([[ 0,  1,  2,  3,  0,  4,  8, 12],
        [ 4,  5, 99,  7,  1,  5,  9, 13]]),
 array([[ 8,  9, 10, 11,  2, 99, 10, 14],
        [12, 13, 14, 15,  3,  7, 11, 15]])]

In [128]:
#spliting by column wise
p=np.split(l,2,axis=1)
p

[array([[ 0,  1,  2,  3],
        [ 4,  5, 99,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2, 99, 10, 14],
        [ 3,  7, 11, 15]])]

In [129]:
#unique()
np.unique(l)

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 99])

In [130]:
np.unique(l,return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 99]),
 array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [135]:
#-----------arthimetic operations------------
arr=np.arange(0,100,10)

In [136]:
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [138]:
arr1 =arr-arr
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [139]:
arr2 = arr + arr
arr2

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [141]:
arr3 = np.sqrt(arr)
arr3

array([0.        , 3.16227766, 4.47213595, 5.47722558, 6.32455532,
       7.07106781, 7.74596669, 8.36660027, 8.94427191, 9.48683298])

In [142]:
np.exp(arr)

array([1.00000000e+00, 2.20264658e+04, 4.85165195e+08, 1.06864746e+13,
       2.35385267e+17, 5.18470553e+21, 1.14200739e+26, 2.51543867e+30,
       5.54062238e+34, 1.22040329e+39])

In [143]:
np.sin(arr)

array([ 0.        , -0.54402111,  0.91294525, -0.98803162,  0.74511316,
       -0.26237485, -0.30481062,  0.77389068, -0.99388865,  0.89399666])

In [144]:
arr>4

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])